name: Nightly E2E Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  playwright_e2e_tests:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      id: run_tests
      continue-on-error: true  # Allow the workflow to continue even if tests fail
      env:
        BASE_URL: 'https://artsenius.github.io/about-me'  # Production URL
      run: |
        # Run tests with JSON and HTML reporters
        npx playwright test || export TEST_EXIT_CODE=$?
        
        # Store test status for later steps
        echo "status=${TEST_EXIT_CODE:-0}" >> $GITHUB_OUTPUT
    
    - name: Generate test report
      if: always()  # Run even if tests fail
      env:
        TEST_STATUS: ${{ steps.run_tests.outputs.status }}
      run: |
        # Map exit code to status
        STATUS="passed"
        if [ "$TEST_STATUS" != "0" ]; then
          STATUS="failed"
        fi
        
        # Generate formatted JSON report (using default paths)
        node reporting/create-test-result-json.js \
          --project "Playwright" \
          --status "$STATUS"
    
    - name: Upload test results to backend
      if: always()  # Run even if tests fail
      env:
        API_URL: 'https://about-me-automation-backend.azurewebsites.net/api'
      run: |
        if [ -f "test-results/playwright-report.json" ]; then
          node reporting/upload-test-result.js \
            --api-url "$API_URL/test-runs"
        else
          echo "ERROR: No test results file found"
          ls -la test-results/
          exit 1
        fi

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
        retention-days: 30
        compression-level: 9  # Maximum compression
        overwrite: true      # Override if exists
