name: Nightly E2E Tests

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 07:00 UTC (12:00 AM PDT) every day
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  repository_dispatch:
    types: [trigger-nightly-tests]

jobs:
  playwright_e2e_tests:
    name: Playwright E2E Tests
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: |
        npx playwright install --with-deps || {
          echo "Failed to install with deps, trying fallback..."
          npx playwright install chromium
        }
    
    - name: Run Playwright tests
      id: run_tests
      continue-on-error: true  # Allow workflow to continue for result upload
      env:
        BASE_URL: 'https://www.arthursenko.com/'  # Production URL
      run: |
        npx playwright test || export TEST_EXIT_CODE=$?
        echo "status=${TEST_EXIT_CODE:-0}" >> $GITHUB_OUTPUT
    
    - name: Generate test report
      if: always()  # Run even if tests fail
      env:
        TEST_STATUS: ${{ steps.run_tests.outputs.status }}
        PROJECT_NAME: ${{ github.event_name == 'schedule' && 'Playwright Nightly Run' || github.event_name == 'workflow_dispatch' && 'Playwright Manual Run' || github.event_name == 'repository_dispatch' && 'Playwright Deployment Validation' || 'Playwright Local Run' }}
      run: |
        STATUS="passed"
        if [ "$TEST_STATUS" != "0" ]; then
          STATUS="failed"
        fi
        node reporting/create-test-result-json.js --status $STATUS --project "$PROJECT_NAME"
    
    - name: Upload test results
      if: always()  # Run even if tests fail
      env:
        TEST_STATUS: ${{ steps.run_tests.outputs.status }}
      run: |
        node reporting/upload-test-result.js
        
    - name: Upload test artifacts
      if: always()  # Run even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 30  # Artifacts will be retained for 30 days
          
    - name: Check test status
      if: always()  # Run as last step
      env:
        TEST_STATUS: ${{ steps.run_tests.outputs.status }}
      run: |
        if [ "$TEST_STATUS" != "0" ]; then
          echo "Tests failed with exit code $TEST_STATUS"
          exit 1
        fi
